const mailer = require('nodemailer')
const pug = require('pug')

const server = 'localhost:3000'

const transport = mailer.createTransport({
  host: 'smtp.mailtrap.io',
  port: 2525,
  auth: {
    user: 'bde6ec1c45e0ce', // generated by Mailtrap
    pass: '013978550e898b' // generated by Mailtrap
  }
})

const mailOptions = {
  from: '"Служба восстановления паролей" <srv@pwd_recover.com>',
  to: '',
  subject: 'Восстановление пароля',
  text: '',
  html: ''
}

exports.sendMail = (to, token, done) => {
  const options = { link: `http://${server}/recover/${token}` }
  mailOptions.to = to
  mailOptions.html = pug.renderFile('./mail_templates/tmpl_main.pug', options)
  transport.sendMail(mailOptions, (error, info) => {
    if (error) {
      console.log(error)
    }
    console.log('Message sent: %s, link: %s', info.messageId, options.link)
    done(info)
  })
}
