const mailer = require('nodemailer');

const transport = mailer.createTransport({
    host: "smtp.mailtrap.io",
    port: 2525,
    auth: {
      user: "bde6ec1c45e0ce", //generated by Mailtrap
      pass: "013978550e898b" //generated by Mailtrap
    }
  });

const mailOptions = {
    from: '"Служба восстановления паролей" <srv@pwd_recover.com>',
    to: '',
    subject: 'Восстановление пароля',
    text: '', 
    html: '' // генерировать по шаблону
};

exports.sendMail = (to) => {
    mailOptions.to = to
    transport.sendMail(mailOptions, (error, info) => {
        if (error) {
          return console.log(error);
        }
        console.log('Message sent: %s', info.messageId);
      });
}